[features]
seeds = false
[programs.devnet]
solana_gif_portal = "6ciy83bMssvDG7TTZzSxb8aRT6F2QBM7rjodDZzH51mA"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/supantha/.config/solana/id.json"

[scripts]
test = "node tests/solana_gif_portal.js"
